import { Character } from "@/types/server";

export const dummyCharacters: Character[] = [
  {
    name: "Crispin Bonehunter",
    mint: "CppHyx5oQ5vGGTEDk3ii5LtdzmAbdAffrqqip7AWWkdZ",
    collection: "OKB POG",
    image:
      "https://storage.googleapis.com/fractal-launchpad-public-assets/pogs/okb/assets/collectors/assets/2557.png",
    experience: {
      Strength: { current: 0, threshold: 1000 },
      Fighting: { current: 0, threshold: 1000 },
      Shooting: { current: 0, threshold: 1000 },
      Athletics: { current: 0, threshold: 1000 },
      Psionics: { current: 0, threshold: 1000 },
      Magic: { current: 0, threshold: 1000 },
      Electronics: { current: 0, threshold: 1000 },
      Forestry: { current: 0, threshold: 1000 },
      Farming: { current: 0, threshold: 1000 },
      Healing: { current: 0, threshold: 1000 },
      Manufacturing: { current: 0, threshold: 1000 },
      Mining: { current: 0, threshold: 1000 },
    },
    skills: {
      Athletics: 1,
      Electronics: 0,
      Farming: 0,
      Fighting: 1,
      Forestry: 0,
      Healing: 1,
      Magic: 1,
      Manufacturing: 0,
      Mining: 1,
      Psionics: 1,
      Shooting: 0,
      Strength: 0,
    },
    army: [],
    attributes: {
      Bear: "Penny",
      Clothing: "Blue OKB Tank",
      Eyewear: "Charcoal",
      FractalRank: 1337,
      FractalRarity: "Common",
      GAMESTATAgility: "2",
      GAMESTATAttack: "4",
      GAMESTATElement: "Water 3",
      GAMESTATMass: "3",
      Headwear: "Jellyfish Pog God Cap",
      Mask: "Mask",
      Neckwear: "Yang",
      OverClothing: "Cloudhaze",
      POGArt: "POG Bears",
      POGEnvironment: "Game Stats Circle Midnight Apple",
      POGMaterial: "Cardboard",
      POGRarity: "Rare",
    },
    // faction: "GqMugi26QUaoLiGHnMAED"

    faction: {
      id: "",
      pubkey: "",
      creator: "",
      name: "",
      image: "",
      external_link: "",
      description: "",
      townhallLevel: 1,
      stations: [
        {
          id: "1",
          faction: "",
          blueprint: "",
          level: "1",
        },
      ],
      lastLooted: "",
      construction: {
        finishedAt: "",
        station: {
          id: "1",
          faction: "",
          blueprint: "",
          level: "1",
        },
      },
    },
  },
  {
    name: "Crispin Bonehunter",
    mint: "CppHyx5oQ5vGGTEDk3ii5LtdzmAbdAffrqqip7AWWkdZ",
    collection: "OKB POG",
    image:
      "https://storage.googleapis.com/fractal-launchpad-public-assets/pogs/okb/assets/collectors/assets/2557.png",
    experience: {
      Strength: { current: 0, threshold: 1000 },
      Fighting: { current: 0, threshold: 1000 },
      Shooting: { current: 0, threshold: 1000 },
      Athletics: { current: 0, threshold: 1000 },
      Psionics: { current: 0, threshold: 1000 },
      Magic: { current: 0, threshold: 1000 },
      Electronics: { current: 0, threshold: 1000 },
      Forestry: { current: 0, threshold: 1000 },
      Farming: { current: 0, threshold: 1000 },
      Healing: { current: 0, threshold: 1000 },
      Manufacturing: { current: 0, threshold: 1000 },
      Mining: { current: 0, threshold: 1000 },
    },
    skills: {
      Athletics: 1,
      Electronics: 0,
      Farming: 0,
      Fighting: 1,
      Forestry: 0,
      Healing: 1,
      Magic: 1,
      Manufacturing: 0,
      Mining: 1,
      Psionics: 1,
      Shooting: 0,
      Strength: 0,
    },
    army: [],
    attributes: {
      Bear: "Penny",
      Clothing: "Blue OKB Tank",
      Eyewear: "Charcoal",
      FractalRank: 1337,
      FractalRarity: "Common",
      GAMESTATAgility: "2",
      GAMESTATAttack: "4",
      GAMESTATElement: "Water 3",
      GAMESTATMass: "3",
      Headwear: "Jellyfish Pog God Cap",
      Mask: "Mask",
      Neckwear: "Yang",
      OverClothing: "Cloudhaze",
      POGArt: "POG Bears",
      POGEnvironment: "Game Stats Circle Midnight Apple",
      POGMaterial: "Cardboard",
      POGRarity: "Rare",
    },
    // faction: "GqMugi26QUaoLiGHnMAED"

    faction: {
      id: "GqMugi26QUaoLiGHnMAED",
      pubkey: "GqMugi26QUaoLiGHnMAED",
      creator: "GqMugi26QUaoLiGHnMAED",
      name: "GqMugi26QUaoLiGHnMAED",
      image: "GqMugi26QUaoLiGHnMAED",
      external_link: "GqMugi26QUaoLiGHnMAED",
      description: "GqMugi26QUaoLiGHnMAED",
      townhallLevel: 1,
      stations: [
        {
          id: "1",
          faction: "GqMugi26QUaoLiGHnMAED",
          blueprint: "GqMugi26QUaoLiGHnMAED",
          level: "1",
        },
      ],
      lastLooted: "GqMugi26QUaoLiGHnMAED",
      construction: {
        finishedAt: "GqMugi26QUaoLiGHnMAED",
        station: {
          id: "1",
          faction: "GqMugi26QUaoLiGHnMAED",
          blueprint: "GqMugi26QUaoLiGHnMAED",
          level: "1",
        },
      },
    },
  },
];
