export interface BattleMemo {
	mint: string // mint of the character
	timestamp: string // timestamp of the battle
	defendingMint: string // mint of the defending character
}

// Generated by https://quicktype.io

export interface BattleHistory {
	histories: History[]
}

export interface History {
	id: string
	attacker: string
	defender: string
	time: string
	winner: string
	result: Result
}

export interface Result {
	rounds: Round[]
	winner: string
}

export interface Round {
	attacker: Attacker
	defender: Defender
}

export interface Attacker {
	roll: number
	unit: AttackerUnit
	bonus: number
}

export interface AttackerUnit {
	name: string
	bonus: PurpleBonus
	image: string
	skill: string
	assetId: string
}

export interface PurpleBonus {
	Wizard: number
	Blademaster: number
}

export interface Defender {
	roll: number
	unit: DefenderUnit
	bonus: number
}

export interface DefenderUnit {
	name: string
	bonus: FluffyBonus
	image: string
	skill: string
	assetId: string
}

export interface FluffyBonus {
	Gunner: number
	Ranger: number
	Brawler: number
	Blademaster: number
}
