import { Box, Text } from "@chakra-ui/react";
import { colors } from "@/styles/defaultTheme";

export const DashboardInfo = () => {
  return (
    <Box
      display="flex"
      justifyContent="space-between"
    >
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginRight="1rem"
      >
        FACTION
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginRight="1rem"
      >
        LEVEL
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginLeft="1rem"
      >
        FACTIONS
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginLeft="1rem"
      >
        TOTAL RFS
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginLeft="1rem"
      >
        PLAYERS
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginLeft="1rem"
      >
        LEADERBOARD
      </Text>
      <Text
        bg={colors.brand.primary}
        borderRadius="0.5rem"
        p="0.25rem"
        fontSize="18px"
        fontWeight={600}
        letterSpacing="3px"
        h="3rem"
        flex="1"
        display="flex"
        alignItems="center"
        justifyContent="center"
        marginLeft="1rem"
      >
        LOGS
      </Text>
    </Box>
  );
};
